apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: s03f74k10-nodejs 
  janus-idp.io/tekton: s03f74k10-nodejs
  backstage.io/kubernetes-id: s03f74k10-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s03f74k10-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  