apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: s03f74k10-nodejs-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/s03f74k10-nodejs-gitops